### ISSUE TITLE
License of this package

### ISSUE THREAD

**Issue by mmodmmod** [brunner-medien/pimcore-plantuml#2]
Dear maintainers & creators of this Pimcore plugin,

I wanted to inform myself which license this plugin is using since I would be interested in using it for commercial use or is it simply free for anyone to use? Would it be possible to provide these information?

Best

**Comment by gadget60** [comment]
This bundle is released under LGPL-3:

https://github.com/brunner-medien/pimcore-plantuml/blob/dbbe402c007d4d1011c113d710615e8b96ddc155/composer.json#L4

Feel free to use it in your commercial projects...

**Comment by mmodmmod** [comment]
Thank you very much! 
Unfortunately, I did not see this
