### ISSUE TITLE
Error 500 when accessing PlantUML view (ClassificationStore data)

### ISSUE THREAD

**Issue by Pierre-Datasolution** [brunner-medien/pimcore-plantuml#3]
Hello

The error occurs apparently when accessing ClassificationStore data

I had to change this method definition to fix this error

> \PlantUmlBundle\Model\AbstractModel::generateClassificationGroupName
> 
> public static function generateClassificationGroupName(string $groupId)
> corrected in
> public static function generateClassificationGroupName($groupId)

All works fine after that...
I don't know if this has to be corrected or if it is a data problem by my side... 
I currently don't have problem with my Classification Store as far as Pimcore is concerned

Working with Pimcore 10.5.14 and PHP 8.1

Thanks a lot for exmining this problem
Pierre

> Timestamp: Fri Mar 17 2023 13:38:19 GMT+0100 (heure normale d’Europe centrale)
> Status: 500 | Internal Server Error
> URL: plantuml/config_get?name=PIM
> Message: PlantUmlBundle\Model\AbstractModel::generateClassificationGroupName(): Argument #1 ($groupId) must be of type string, int given, called in /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Generator/Structure/ClassificationStoreGenerator.php on line 46
> Trace: 
> in /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Model/AbstractModel.php:30
> #0 /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Generator/Structure/ClassificationStoreGenerator.php(46): PlantUmlBundle\Model\AbstractModel::generateClassificationGroupName(1)
> #1 /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Generator/Traits/FieldDefinitionTrait.php(23): PlantUmlBundle\Generator\Structure\ClassificationStoreGenerator->generate(Array, false)
> #2 /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Generator/Root/ClassGenerator.php(29): PlantUmlBundle\Generator\Root\ClassGenerator->processFieldDefinitions(Object(PlantUmlBundle\Model\ClassModel), Array, Array, false)
> #3 /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Service/GeneratorService.php(78): PlantUmlBundle\Generator\Root\ClassGenerator->generate(Array, false)
> #4 /home/DEV/releases/285860/vendor/brunner-medien/pimcore-plantuml/src/Controller/Admin/PlantUmlController.php(76): PlantUmlBundle\Service\GeneratorService->loadRegistry()
> #5 /home/DEV/releases/285860/vendor/symfony/http-kernel/HttpKernel.php(163): PlantUmlBundle\Controller\Admin\PlantUmlController->getConfigAction(Object(Symfony\Component\HttpFoundation\Request), Object(PlantUmlBundle\Service\GeneratorService), Object(PlantUmlBundle\Service\ConfigurationService))
> #6 /home/DEV/releases/285860/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
> #7 /home/DEV/releases/285860/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
> #8 /home/DEV/releases/285860/public/index.php(40): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
> #9 {main}

**Comment by gadget60** [comment]
Fixed with 87e4207b5c9237e1e00c26534fe3573015fb5be4 / version 1.1.5, thanx for reporting!
